### PR TITLE
Website documentation for OpenStack4j 3.0.0

### PR DESCRIPTION
**Pull request by auhlig**
This will update the website to reflect OS4j 3.0.0 .

What do you think @gondor , @dhague ?

### CODE REVIEW

**Comment by gondor** [comment]
LGTM! Thanks for updating this

**Comment by auhlig** [comment]
Not sure how I managed to get the test for the docs failing but I'll look into this in the evening.

**Comment by gondor** [comment]
its all good.. Don't worry about it.  I recently have it continuously deploying to me Mesos cluster where this runs.  I forgot to display this trigger on PR's and so the deployment secrent's aren't available on the deploy.

**Comment by gondor** [comment]
@auhlig getting ready to release.  Can you check into the merge conflicts?

**Comment by auhlig** [comment]
@gondor: Done. Looks better now?

**Comment by gondor** [comment]
Looks good!  Can we cancel this PR and can you PR and then Merge into a new V3 branch I created vs master?  

The issue is anything that goes to master gets deployed automatically via Docker.

I want to make a few additions right before we cut the release so that V3 is the "latest stable" and primary release and V2 is maintenance with no future develop.

**Comment by auhlig** [comment]
Sure. Will do.

**Pull request closed without merging**
